spring.application.name=rill
server.port=8080
app.web.cors.allowed-origins=http://localhost:5173
spring.datasource.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/rill_app}
spring.datasource.username=${APP_DB_USERNAME:postgres}
spring.datasource.password=${APP_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
mybatis-plus.configuration.map-underscore-to-camel-case=true
