create table if not exists app_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    email varchar(256) not null unique,
    display_name varchar(128) not null,
    password varchar(128) not null,
    role varchar(32) not null,
    kernel_db_name varchar(128) not null,
    email_verified boolean not null,
    kernel_db_provisioned boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists app_jwt_session (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    jwt_id varchar(64) not null unique,
    expires_at timestamp not null,
    revoked boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index if not exists idx_app_jwt_session_user_id on app_jwt_session (user_id);

create table if not exists app_verification_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    purpose varchar(64) not null,
    token varchar(128) not null unique,
    expires_at timestamp not null,
    used boolean not null,
    created_at timestamp not null,
    used_at timestamp
);

create index if not exists idx_app_verification_token_user_id on app_verification_token (user_id);

create table if not exists workspace_session (
    session_id varchar(64) primary key,
    owner_id bigint not null,
    current_database varchar(128) not null,
    created_at timestamp not null,
    last_used_at timestamp not null
);

create table if not exists query_history (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    session_id varchar(64) not null,
    trace_id varchar(64) not null,
    db_name varchar(128) not null,
    sql_text text not null,
    success boolean not null,
    elapsed_ms bigint not null,
    executed_at timestamp not null
);

create index if not exists idx_query_history_session_id on query_history (session_id);

create table if not exists sql_snippet (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    title varchar(128) not null,
    description varchar(512),
    sql_text text not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists demo_scenario (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    title varchar(128) not null,
    description varchar(512),
    sql_script text not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists export_task (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    title varchar(128) not null,
    description varchar(512),
    db_name varchar(128) not null,
    sql_text text not null,
    export_format varchar(16) not null,
    status varchar(32) not null,
    output_path varchar(512),
    last_error varchar(1024),
    created_at timestamp not null,
    updated_at timestamp not null,
    completed_at timestamp
);
