brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# For local development keep 127.0.0.1.
# On Debian server replace this with the server's public IP or resolvable hostname.
brokerIP1 = 127.0.0.1
